"""The simulated backend: a :class:`Plant` behind the backend interface.

This is not a mock.  It exposes exactly the primitives :class:`RealBackend`
exposes, so the motion FSM, the speed profile, the gate and the whole UI run
against it unmodified.  Everything exercised in simulation is the production
code path; only the physics underneath is different.

Time
----
The plant has no clock of its own (:mod:`litearm_studio_daemon.gripper.backend.plant` is a
pure function of ``dt``), so this class owns the wall clock and integrates
whatever elapsed between calls.  Both :meth:`stream_frame` and :meth:`poll`
advance it, which matters: a real motor emits status frames whether or not
anyone transmits, so a link-health display driven only by transmitted frames
would show a false drop-out whenever the gripper sat still.  Advancing on poll
as well means the simulator behaves the same way.

The clock is injectable so tests can drive the physics deterministically
instead of sleeping.
"""

from __future__ import annotations

import random
import time
from pathlib import Path
from typing import Any, Callable

from .. import calibration, constants
from ..calibration import CalibrationInfo
from ..telemetry import Telemetry
from ..units import Limits, derive_scale
from . import ConnectFailed, FaultActive, GripperBackend, NotReady, WriteZeroResult
from .plant import Plant, PlantConfig


def default_sim_calibration_path() -> Path:
    """A simulator-specific calibration path.

    Deliberately NOT ``calibration.default_user_path()``.  The simulator's
    "save calibration" button must never be able to overwrite the calibration
    of the real gripper sitting on the bench — that file is the one piece of
    data here that cannot be regenerated by re-running anything.
    """
    return Path.home() / ".litegrip" / "litegrip_calibration.sim.json"


class SimBackend(GripperBackend):
    """A gripper that exists only in software."""

    #: The master ID a stock LiteGrip ships with (see :meth:`master_id`).
    _MASTER_ID = 0x18

    def __init__(
        self,
        config: PlantConfig | None = None,
        *,
        clock: Callable[[], float] | None = None,
        calibration_path: str | Path | None = None,
        pinned_path: str | Path | None = None,
        limits: Limits | None = None,
        realtime: bool = True,
        channel: str = "can0",
        mount: str | None = None,
        enable_delay_s: float = 0.0,
        jitter_ms: float = 0.0,
        no_frames: bool = False,
        tx_fail: bool = False,
        uv: bool = False,
        seed: int | None = None,
    ) -> None:
        super().__init__()
        self.plant = Plant(config)
        self.config = self.plant.config
        self._clock = clock or time.monotonic
        self._last_t = self._clock()
        self._realtime = realtime
        self._rng = random.Random(seed)
        #: The daemon's device identity, so the simulator resolves calibrations
        #: through the same §5.3 order the real backend uses.
        self._channel = channel
        self._mount = mount

        # Fault injection.
        self.enable_delay_s = enable_delay_s
        self.jitter_ms = jitter_ms
        self.no_frames = no_frames
        self.tx_fail = tx_fail
        self.uv = uv

        self._connected = False
        self._enabled = False

        #: The simulator's *own* file, written by ``save_calibration`` — never the
        #: bench unit's, which is the one piece of data here that cannot be
        #: regenerated by re-running anything.
        self.calibration_path = Path(calibration_path) if calibration_path else default_sim_calibration_path()
        #: The file the daemon's per-channel record pins (§5.3 row 1).  Kept
        #: apart from ``calibration_path`` on purpose: the pinned file is read,
        #: the simulator's own file is written.
        self._pinned = Path(pinned_path) if pinned_path else None

        # The plant starts matched to the example user calibration it was built
        # from, so a bare simulator is immediately usable and, importantly, is
        # NOT in the reversed uncalibrated state.
        if limits is not None:
            self.plant.limits = limits
        self._info = self._resolve_and_apply()

    # ── lifecycle ───────────────────────────────────────────────────────────
    def connect(self) -> None:
        self._claim()
        self._advance()
        self._connected = True
        self._last_t = self._clock()

    def disconnect(self) -> None:
        self._claim()
        self._enabled = False
        self._connected = False

    def enable(self) -> None:
        self._claim()
        self._require_connected()
        if self.uv:
            self._raise_uv()
        if self.enable_delay_s > 0 and self._realtime:
            # The real enable() retries five times over up to ten seconds.
            self._sleep(self.enable_delay_s)
        self._advance()
        self._enabled = True

    def disable(self) -> None:
        """Cut the torque and stop listening.

        The plant is explicitly unloaded first.  A real driver that is disabled
        stops applying whatever the last frame asked for; the plant has no notion
        of being enabled, so without this it would go on squeezing at the last
        commanded torque for ever, and every test of a disabled gripper would be
        testing a gripper that is still holding.
        """
        self._claim()
        self._advance()
        if self._connected and self._enabled:
            self.plant.stream(self.plant.q, 0.0, 0.0, 0.0, 0.0)
        self._enabled = False

    def clear_fault(self) -> None:
        self._claim()
        self._advance()
        if self.uv:
            self._raise_uv()

    # ── control-rate primitives ─────────────────────────────────────────────
    def stream_frame(
        self,
        q_rad: float,
        kp: float,
        kd: float,
        dq_rad_s: float = 0.0,
        tau_nm: float = 0.0,
        *,
        ungated: bool = False,
    ) -> bool:
        # ``ungated`` is accepted and ignored.  It relaxes checks the simulator
        # does not have: the plant is a set of differential equations, not a CAN
        # bus, so there is nothing in it that depends on a calibration being
        # right or on a target being inside one.  Refusing here instead would
        # make an ungated frame behave differently on the two backends, which is
        # the one thing the simulator must never do.
        del ungated
        self._claim()
        self._advance()
        if not self._connected or not self._enabled:
            return False
        if self.tx_fail:
            return False
        self.plant.stream(q_rad, kp, kd, dq_rad_s, tau_nm)
        return True

    def poll(self) -> bool:
        self._claim()
        self._advance()
        if not self._connected or not self._enabled:
            return False
        if self.no_frames:
            return False
        return self.plant.poll()

    def read(self) -> Telemetry:
        # Deliberately does not advance time: ``read`` is documented as
        # non-blocking, and the worker calls it once per tick after polling.
        self._claim()
        tele = self.plant.snapshot(self._clock())
        if not self._enabled:
            return Telemetry(
                position_rad=tele.position_rad,
                velocity_rad_s=tele.velocity_rad_s,
                torque_nm=0.0,
                temperature_mos=tele.temperature_mos,
                temperature_coil=tele.temperature_coil,
                error_code=constants.ERROR_DISABLED,
                position_mm=tele.position_mm,
                force_n=0.0,
                t=tele.t,
            )
        if self.uv:
            return Telemetry(
                position_rad=tele.position_rad,
                velocity_rad_s=tele.velocity_rad_s,
                torque_nm=tele.torque_nm,
                temperature_mos=tele.temperature_mos,
                temperature_coil=tele.temperature_coil,
                error_code=constants.ERROR_UV,
                position_mm=tele.position_mm,
                force_n=tele.force_n,
                t=tele.t,
            )
        return tele

    def zero_torque(self) -> None:
        """Command zero torque, staying enabled and back-drivable.

        The motor keeps listening: this mirrors ``LiteGrip.stop()``, which sends
        ``kp=kd=0`` and nothing else.  It is emphatically not ``disable()`` —
        a console that could not re-command the axis after a stop would have to
        be re-enabled for every one, and the sim would be the only place that
        behaved that way.
        """
        self._claim()
        self._advance()
        if self._connected and self._enabled:
            self.plant.stream(self.plant.q, 0.0, 0.0, 0.0, 0.0)

    # ── calibration ─────────────────────────────────────────────────────────
    def load_calibration(self, path: str | None = None,
                         template: str | None = None) -> bool:
        """Resolve through the daemon's §5.3 order, on the simulator's terms.

        Explicit loads — a template name, or a path the operator imported — go
        through the shared resolution, so the calibration page is exercised for
        real here, including the reversed, malformed and channel-mismatch cases.

        With neither argument the answer is the simulator's *own* file, or its
        own limits when there is none.  It deliberately does not walk the shared
        order to the end: the bench unit's calibration is the one piece of data
        in this program that cannot be regenerated, and a simulator that read it
        would report another machine's geometry while looking perfectly healthy.
        """
        self._claim()
        self._info = self._resolve_and_apply(path, template)
        return self._info.usable

    def save_calibration(self, path: str | None = None) -> str:
        self._claim()
        info = self._info
        if info is None or info.limits is None:
            raise NotReady("没有可保存的标定")
        target = path or self.calibration_path
        data = calibration.build_save_dict(info.limits, channel=self._channel)
        for key in ("channel", "can_id", "mst_id", "canfd_mode", "motor_type"):
            if key in info.raw:
                data[key] = info.raw[key]
        written = calibration.write_calibration(target, data)
        # Read back what was just written, for the same reason the real backend
        # does: an in-memory probe result only stops being in memory once it has
        # been read off the disk it was just written to, and that read is the
        # only thing that promotes the provenance and opens the gate.  Without
        # it the simulator writes the file and goes on reporting
        # ``in_memory_unsaved``, so an operator who has calibrated and saved —
        # the entire point of the guided probe — still faces a console that
        # refuses to move.  A simulator that behaves differently from the
        # hardware is the one thing this backend must never be.
        self._info = self._resolve_and_apply(written)
        return written

    def master_id(self) -> int | None:
        """The master ID the simulated motor answers on.

        The simulator stands in for a stock LiteGrip, whose status frames arrive
        on ``0x18`` — the SDK's own default and the value its auto-detect lands
        on for an unconfigured unit (``can/controller.py``'s fallback).  So it
        reports the same ID the real backend would detect, rather than ``None``:
        a simulator that behaved differently from the hardware is the one thing
        this backend must never be.
        """
        return self._MASTER_ID

    def calibration_info(self) -> CalibrationInfo | None:
        return self._info

    def set_calibration_memory(
        self, zero_rad: float, open_rad: float, rad_to_mm: float, max_stroke_mm: float | None = None
    ) -> CalibrationInfo:
        """Adopt fresh probe results without saving them (sim only)."""
        self._claim()
        stroke = max_stroke_mm if max_stroke_mm is not None else self.plant.limits.max_stroke_mm
        info = calibration.in_memory(zero_rad, open_rad, rad_to_mm, stroke)
        self._info = info
        if info.limits is not None:
            self._apply_limits(info.limits)
        return info

    def set_calibration_path(self, path: str | None) -> None:
        """Pin the file this channel resolves to (§5.3 row 1)."""
        self._claim()
        self._pinned = Path(path) if path else None

    def write_zero(self) -> WriteZeroResult:
        """Re-zero the encoder in software (the 0xFE write, made observable).

        The plant keeps integrating the same physical angle; only what the
        encoder *reports* shifts, by the angle current at the moment of the
        write.  Modelled rather than stubbed because write-zero is exercised
        end-to-end in simulation, and a no-op would let a re-zero that should
        have invalidated the loaded calibration pass unnoticed.
        """
        self._claim()
        self._require_connected()
        if not self._enabled:
            raise NotReady("尚未使能")
        before = self.plant.reported_q()
        self.plant.zero_offset_rad = self.plant.q
        return WriteZeroResult(before_rad=before, after_rad=self.plant.reported_q(),
                               ok=True)

    def set_mount(self, mount: str | None) -> None:
        """Record the declared mounting direction (§5.3 row 5)."""
        self._claim()
        self._mount = mount

    def set_travel_mm(self, max_stroke_mm: float) -> None:
        """Set the travel, and re-derive the scale from it and the plant's angles.

        The re-derivation is what a real backend gets from re-resolving the
        calibration file, and it matters for the same reason: the travel decides
        the millimetres per rad, so a simulated gripper that kept the old scale
        would go on reporting its jaws as wider or narrower than they are.
        """
        self._claim()
        limits = self.plant.limits
        self.plant.limits = Limits(
            limits.closed_rad,
            limits.open_rad,
            derive_scale(limits.travel_rad, max_stroke_mm),
            float(max_stroke_mm),
        )
        self.plant.q = self.plant.limits.clamp_rad(self.plant.q)

    def limits(self) -> Limits:
        return self.plant.limits

    def describe(self) -> str:
        return f"仿真 (Plant) | {self._info.label if self._info else '未标定'}"

    # ── fault injection ─────────────────────────────────────────────────────
    def inject(self, **kwargs: Any) -> None:
        """Set plant conditions or faults by keyword.

        ``obj_mm``      obstruction between the jaws at this opening (None clears)
        ``uv``          latch an undervoltage fault; ``enable`` then raises
        ``no_frames``   stop emitting status frames (the link looks dead)
        ``tx_fail``     refuse transmitted frames
        ``enable_delay_s``  seconds ``enable()`` takes
        ``jitter_ms``   ± jitter applied to the integrated step
        ``reset``       reset the plant to the powered-off pose
        """
        self._claim()
        if kwargs.pop("reset", False):
            self.plant.reset()
        if "obj_mm" in kwargs:
            self.plant.object_mm = kwargs.pop("obj_mm")
        for key in ("uv", "no_frames", "tx_fail"):
            if key in kwargs:
                setattr(self, key, bool(kwargs.pop(key)))
        if "enable_delay_s" in kwargs:
            self.enable_delay_s = float(kwargs.pop("enable_delay_s"))
        if "jitter_ms" in kwargs:
            self.jitter_ms = float(kwargs.pop("jitter_ms"))
        if kwargs:
            raise TypeError(f"未知的注入参数: {', '.join(sorted(kwargs))}")

    # ── internals ───────────────────────────────────────────────────────────
    def _advance(self) -> None:
        """Integrate the plant over the time since the last call."""
        now = self._clock()
        dt = now - self._last_t
        self._last_t = now
        if dt <= 0.0:
            return
        # A process that was descheduled (or a paused GUI) must not be able to
        # fast-forward the physics; the gripper would teleport across its
        # travel in one step.
        if dt > constants.SIM_MAX_STEP_S:
            dt = constants.SIM_MAX_STEP_S
        if self.jitter_ms > 0.0:
            j = self.jitter_ms / 1000.0
            dt *= 1.0 + self._rng.uniform(-j, j)
        if dt > 0.0:
            self.plant.step(dt)

    def _sleep(self, seconds: float) -> None:
        """Block in real time, or advance an injected clock by ``seconds``."""
        if self._clock is time.monotonic:
            time.sleep(seconds)
        else:
            # Deterministic tests supply their own clock; jumping it forward is
            # the equivalent of waiting without the wall-clock cost.
            self._advance()
            self._last_t += seconds

    def _require_connected(self) -> None:
        if not self._connected:
            raise ConnectFailed("尚未连接")

    def _raise_uv(self) -> None:
        raise FaultActive(
            constants.ERROR_UV,
            f"{constants.describe_error(constants.ERROR_UV)}（仿真注入）",
        )

    def _resolve_and_apply(self, path: str | None = None,
                           template: str | None = None) -> CalibrationInfo:
        """Resolve and apply a calibration, on the simulator's own terms.

        An explicit ``path`` or ``template`` goes through the shared §5.3
        resolution, so a template's nominal geometry and an imported file's
        validation behave here exactly as they do on the bench.

        ``None``/``None`` means "whatever this simulator's file says", and when
        that file does not exist the answer is the plant's own limits — not a
        search that would end at the bench gripper's file or at the SDK's factory
        data.  Both endings are wrong here: the bench file is the one thing in
        this program that cannot be regenerated, and the simulator has a file of
        its own so that it never reads or writes it; and factory data reports
        factory provenance, which the gate only lets through after the operator
        acknowledges that the numbers may belong to a different gripper — a
        statement that is not true of a simulator whose numbers are its own.
        """
        if path is None and template is None:
            if self._pinned is not None and self._pinned.is_file():
                info = calibration.resolve(
                    self._channel, path=str(self._pinned),
                    travel_mm=self.plant.limits.max_stroke_mm)
            elif self.calibration_path.is_file():
                info = calibration.resolve(
                    self._channel, path=str(self.calibration_path),
                    travel_mm=self.plant.limits.max_stroke_mm)
            else:
                # No file of its own.  A *declared* mount decides, exactly as it
                # does on the real backend: resolution row 5 answers with the
                # matching template.  Nothing else is consulted, and in
                # particular the SDK's factory file is not — factory provenance
                # says "these numbers may belong to another gripper", which is
                # not true of a simulator whose numbers are its own, and it would
                # leave `--fake` behind a gate that demands an acknowledgement
                # nobody can give.
                if self._mount in calibration.TEMPLATE_NAMES:
                    info = calibration.resolve(
                        self._channel, mount=self._mount,
                        travel_mm=self.plant.limits.max_stroke_mm)
                else:
                    info = self._default_info()
        else:
            info = calibration.resolve(
                self._channel, path=path, mount=self._mount, template=template,
                travel_mm=self.plant.limits.max_stroke_mm)
        if info.limits is not None:
            self._apply_limits(info.limits)
        return info

    def _default_info(self) -> CalibrationInfo:
        """The calibration of a simulator that has no file of its own.

        Built from the plant, and marked as a *user* calibration because that is
        what it is: numbers that describe this gripper, rather than data that may
        belong to another one.  The warning is what tells the operator that
        nothing here survives a restart.
        """
        limits = self.plant.limits
        return calibration.CalibrationInfo(
            provenance=calibration.PROVENANCE_USER,
            limits=limits,
            path=str(self.calibration_path),
            raw={
                "zero_position_rad": limits.closed_rad,
                "max_position_rad": limits.open_rad,
                "travel_range_rad": limits.travel_rad,
                "rad_to_mm": limits.rad_to_mm,
            },
            warnings=(
                f"仿真默认标定（{self.calibration_path} 不存在）；改参数请在标定页保存",
            ),
            max_stroke_mm=limits.max_stroke_mm,
        )

    def _apply_limits(self, limits: Limits) -> None:
        self.plant.limits = limits
        # Keep the simulated axis inside its (possibly new) travel rather than
        # letting a calibration change strand it outside the hard stops.
        self.plant.q = limits.clamp_rad(self.plant.q)
        self.plant.dq = 0.0
